// Generated by typings
// Source: typings/custom/reactstrap.d.ts
declare module 'reactstrap' {
﻿import * as React from 'react';

module 'reactstrap' {
    export class Alert extends React.Component<any, any> { }
    export class Container extends React.Component<any, any> { }
    export class Row extends React.Component<any, any> { }
    export class Col extends React.Component<any, any> { }
    export class Navbar extends React.Component<any, any> { }
    export class NavbarBrand extends React.Component<any, any> { }
    export class NavbarToggler extends React.Component<any, any> { }
    export class Nav extends React.Component<any, any> { }
    export class NavItem extends React.Component<any, any> { }
    export class NavDropdown extends React.Component<any, any> { }
    export class NavLink extends React.Component<any, any> { }
    export class Breadcrumb extends React.Component<any, any> { }
    export class BreadcrumbItem extends React.Component<any, any> { }
    export class Button extends React.Component<any, any> { }
    export class ButtonDropdown extends React.Component<any, any> { }
    export class ButtonGroup extends React.Component<any, any> { }
    export class ButtonToolbar extends React.Component<any, any> { }
    export class Dropdown extends React.Component<any, any> { }
    export class DropdownItem extends React.Component<any, any> { }
    export class DropdownMenu extends React.Component<any, any> { }
    export class DropdownToggle extends React.Component<any, any> { }
    export class Fade extends React.Component<any, any> { }
    export class Badge extends React.Component<any, any> { }
    export class Card extends React.Component<any, any> { }
    export class CardLink extends React.Component<any, any> { }
    export class CardGroup extends React.Component<any, any> { }
    export class CardDeck extends React.Component<any, any> { }
    export class CardColumns extends React.Component<any, any> { }
    export class CardBlock extends React.Component<any, any> { }
    export class CardFooter extends React.Component<any, any> { }
    export class CardHeader extends React.Component<any, any> { }
    export class CardImg extends React.Component<any, any> { }
    export class CardImgOverlay extends React.Component<any, any> { }
    export class CardSubtitle extends React.Component<any, any> { }
    export class CardText extends React.Component<any, any> { }
    export class CardTitle extends React.Component<any, any> { }
    export class Popover extends React.Component<any, any> { }
    export class PopoverContent extends React.Component<any, any> { }
    export class PopoverTitle extends React.Component<any, any> { }
    export class Progress extends React.Component<any, any> { }
    export class Modal extends React.Component<any, any> { }
    export class ModalHeader extends React.Component<any, any> { }
    export class ModalBody extends React.Component<any, any> { }
    export class ModalFooter extends React.Component<any, any> { }
    export class TetherContent extends React.Component<any, any> { }
    export class Tooltip extends React.Component<any, any> { }
    export class Table extends React.Component<any, any> { }
    export class ListGroup extends React.Component<any, any> { }
    export class Form extends React.Component<any, any> { }
    export class FormFeedback extends React.Component<any, any> { }
    export class FormGroup extends React.Component<any, any> { }
    export class FormText extends React.Component<any, any> { }
    export class Input extends React.Component<any, any> { }
    export class InputGroup extends React.Component<any, any> { }
    export class InputGroupAddon extends React.Component<any, any> { }
    export class InputGroupButton extends React.Component<any, any> { }
    export class Label extends React.Component<any, any> { }
    export class Media extends React.Component<any, any> { }
    export class Pagination extends React.Component<any, any> { }
    export class PaginationItem extends React.Component<any, any> { }
    export class PaginationLink extends React.Component<any, any> { }
    export class TabContent extends React.Component<any, any> { }
    export class TabPane extends React.Component<any, any> { }
    export class Jumbotron extends React.Component<any, any> { }
    export class Collapse extends React.Component<any, any> { }
    export class ListGroupItem extends React.Component<any, any> { }
    export class ListGroupItemText extends React.Component<any, any> { }
    export class ListGroupItemHeading extends React.Component<any, any> { }
    export class UncontrolledAlert extends React.Component<any, any> { }
    export class UncontrolledButtonDropdown extends React.Component<any, any> { }
    export class UncontrolledDropdown extends React.Component<any, any> { }
    export class UncontrolledNavDropdown extends React.Component<any, any> { }
    export class UncontrolledTooltip extends React.Component<any, any> { }
    export class UncontrolledPopover extends React.Component<any, any> { }
}
}
