// Generated by typings
// Source: typings/custom/react-codemirror.d.ts
declare module 'react-codemirror' {
﻿import * as React from 'react';

module 'react-codemirror' {
    export default class CodeMirror extends React.Component <any, any> {}
}
}
