// Generated by typings
// Source: typings/custom/react-copy-to-clipboard.d.ts
declare module 'react-copy-to-clipboard' {
﻿import * as React from 'react';

module 'react-copy-to-clipboard' {
    export default class CopyToClipboard extends React.Component<any, any> { }
}
}
