// Generated by typings
// Source: typings/custom/Formsy.d.ts
import * as React from 'react';

declare module "formsy-react" {

    export interface ValidationErrors {
        [key: string]: string;
    }

    // This is declared for a reference to Formsy.Mixin in FormsyFormComponent.ts
    var Mixin: any;
    var validations: any;

    export function addValidationRule(name, func): void;

    export class Form extends React.Component<any, any> { }

    export function HOC(component): any;
}