// Generated by typings
// Source: typings/custom/Formsy.d.ts
import * as React from 'react';

declare module "react-autosuggest" {
    export default class Autosuggest extends React.Component<any, any> { }
}