// Generated by typings
// Source: typings/custom/react-codemirror2.d.ts
declare module 'react-codemirror2' {
﻿import * as React from 'react';

module 'react-codemirror2' {
    export default class CodeMirror extends React.Component <any, any> {}
}
}
