// Generated by typings
// Source: typings/custom/react-autosuggest.d.ts
declare module 'react-autosuggest' {
﻿// Generated by typings
// Source: typings/custom/Formsy.d.ts
import * as React from 'react';

module 'react-autosuggest' {
    export default class Autosuggest extends React.Component<any, any> { }
}
}
