version: '2.4'
services:
  haproxy_image_service:
    image: eeacms/haproxy
    depends_on:
    - image_service
    networks:
      - image-service-net
    ports:
    - "3000:5000"
    - "1936:1936"
    environment:
      BACKENDS: "image_service:3000"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"

  haproxy_cms:
    image: eeacms/haproxy
    depends_on:
    - cms_arragro_com
    ports:
    - "3001:5000"
    - "1937:1936"
    networks:
      - cms-net
    environment:
      BACKENDS: "cms_arragro_com:5000"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
      # COOKIES_ENABLED: "true"
      # BALANCE: "rdp-cookie"
      HTTPCHK: GET /web-info/799c809f-9ca4-47ca-a9b1-3bce5c5215cf

  haproxy_www:
    image: eeacms/haproxy
    depends_on:
    - www_arragro_com
    networks:
      - cms-net
    ports:
    - "3002:5000"
    - "1938:1936"
    environment:
      BACKENDS: "www_arragro_com:5001"
      DNS_ENABLED: "true"
      LOG_LEVEL: "info"
      HTTPCHK: GET /web-info/60aa42a9-6a6d-49ef-92c3-6c35ec124f0c

  cms_arragro_com:
    image: docker.arragro.com/cms.arragro.com:v0.0.10-alpha
    # logging:
    #   driver: none
    # ports:
    # - 5000:5000
    depends_on:
      - image_service
      - postgres
      - redis
      - azurite
    restart: always
    networks:
      - redis-net
      - image-service-net
      - azurite-net
      - cms-net
    environment:
      - ConnectionStrings:CmsDatabaseConnection=host=postgres;port=5432;database=arragro-cms;user id=postgres;password=Password1;
#      - ConnectionStrings:CmsDatabaseConnection=data source=sql;initial catalog=ArragroCMS;MultipleActiveResultSets=True;App=EntityFramework;User Id=sa;Password=@rr@gr0SuperPassword1;
      - ConnectionStrings:StorageConnection=BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - ConnectionStrings:RedisConnection=redis:6379
      - ApplicationSettings:ImageServiceUrl=http://image_service:3000
      - ApplicationSettings:OverrideAssetUrl=http://127.0.0.1:10000/devstoreaccount1
      - ApplicationSettings:DatabaseType=Postgres
#      - ApplicationSettings:DatabaseType=SqlServer
      - ApplicationSettings:DapperSchema=public
      - DataProtectionSettings:UseDataProtection=true
      - DataProtectionSettings:ApplicationName=cms.arragro.com
      - DataProtectionSettings:UseX509=true
      - DataProtectionSettings:CertBase64=MIIQqQIBAzCCEG8GCSqGSIb3DQEHAaCCEGAEghBcMIIQWDCCBocGCSqGSIb3DQEHBqCCBngwggZ0AgEAMIIGbQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQI+LPToZEqmYgCAggAgIIGQFmxK5QH/zfEAwsgNobi0Dr/+VDtILLmXRaPa8UchZGBlEuvBB8mJ4LttK3jKWh1PBuul1z8tOqPhwcWMYZO3Hfc573pyJVnTgSRst3LYJuLLEx5CoNMWYb0Q1qc0E1qIb83+85mMYYBenGatTJxv3uDxJ4YVA3/OFGfPiqlOqAY4SfHhLcWRS6fEKYU7z4yTFugPX6nZP5xt0bMcPWYHwXeKzIqDF9uOVmnT2VMx6+tXqFbIuSG64po3gH+lC89KBncpaiLv04bgr4tVYJfRjfIXOzNbaYdtxXi13JikoXH6/WYCylGEedkqcuez+L8lHSRyW55NMFX67jAli86I0IwfyYCwGrelOCdVfgfO1u+XLXkMMZYVCKBMz2UtJUSw/4iUYrpRsjMG0hX4ciMX4hzsmcrgAUjtoEck3gTHyB1LrBw/zBnPVSbf/Fa5RgaLJure9Oo/0WMxDcxex2SIRRtky6iCEy5sG+Ubt6ixT8Oup8vZbH6+p4ZkV/ESTaakptjnhJNMWzdhx5ByhskLLVNzE/KKb7HfQrgstT49GxInUWhpy/SLpxAecm0j+rsX1n1mFaxF7w1eq4+p2b66YqlSBdYcFPYOT2GLEyU/7IHfpcan9vxT3/Meudzz1lw5/4kS/z5aeriX0l9jGAXpatT1teGpOMOZr3/3mIcRaalHEoaSKop2J3tiYR/3rdnPt7FC8mESKb8tDOckYrrmKd4D1m1WFdquJ2vNN80C0Kb5pmNIpxa0d88t7pHUVt2X6+u3DQldbqbU/eRYJQJxSCo4rYEb0PsEheJcIQSi6iBlh+lhdReFMS3rt9PzGBSo7KqoiWbjAWfytzl/dnPcMyMHt3GYtSAZI6xUjH2SV3JcGBm8Swhj6r393/CwEG0XRklnIuYv6lgwrJMPqvaduiu2qQK4EonlbRCApcjLjHgUIofG2VfPNNYLPp5OSXWmLdXWIcy/qomu5sibckqbTR1BEqw3fA2ijbMO1Wn30a35PngUX+zbYFkt72VuX49truSWHUpMXtcoeCwF4WlPFM4CVO8gHwSfJaj25oawqLeyyeImh8Fcbb208kJxNH6TRJ6lWOlBX7hwRk+DHFqFDdYtW9oy5Hgty9zILx7QWgpEKeuqiFzgc8/xrJ/qBHhpWkYpG74uQ92Q8qlQA97zV7aiHGoKjWrAa83WFf+M0DH1K0bztVpH+9uaXsSL50x0IPkla9CX2MUwGn1plUJROB3wilZqZ+trI+92SY3/e/2NlQYBhKPKgXcUvL37NYOdE+lyz7iiZdPsWDLVDpjn6+ANUqUQgciXOiwGsz3kkaabTdhATWveL5iUy22xCyk/oQfKgvfp8xuPdBjZP8upKl/nGqMkdqrxs9GhbGkpiFeRnpEfCPqW5gt7H3YNKgSOByOd3NxpzzHvpKzuO+GmgQF1vFiBfnK1AABgG8Cj8n67XMt6UvJqaEzUEbQ1fKd8mfWYPV/e9MIlx6HXuuNdzW5HqgkwhkKL8Dkwae+YZG+uTnKqI2TLgm0K1uC+clxDFmWsnOmZsYNL2eElA3TxdmYcz28FjTUcjD/X+KBJzG3g+JxnQZmrldUb0flVN+0cAZrjdJd3N1oZ+Mno+Ib9ViWqh90SEea288yliDm4mZnh6hnPz2aghFuYWRvUesQ00Bq5eBLCEqaVG4RFD2TGWswDdmbgU8K4PkbKQYnOX8Do0F4c+oXBgSVvXfmOtGivOW06otJdUjCAYGmjtM1SEgrYxhfnQsk+Kt2YesTLVrccdLqdNhZIsTgN0b0aE+6AD/pO/6sWD205gpgPo5KvQfyVxlhtxvXKiLoPhXRRv3yXx2j8sRfCiTuE0bHIZXevPJtYRIlL6uiXKT9yA1qdGorMf34F4HGL5mP0pwsb8M2mkgvwSrNtRVQ0Etl+oUaQ417ilCcub/d+tGGw6Rt7GlKoaqbqitNv/RkUPmcexYuy08Egi2BGx456neehgcyyy0CWn/ocfPXnj8TjUjMdZtBL0/zas2GxK1pkUpCn56IENuPimeiXKn4XlnmhzvsovrzSh56i1wHuXahBDVd8uVCZWbAUAPJ1jaSK6/tjU/JDiki/Zh32heAoxs90XID1CrqEOpFy42kAAk6N+n0b6gwggnJBgkqhkiG9w0BBwGgggm6BIIJtjCCCbIwggmuBgsqhkiG9w0BDAoBAqCCCXYwgglyMBwGCiqGSIb3DQEMAQMwDgQI0zaY/B5O5yUCAggABIIJUISD2t32qMnz8upGYdC0M7HZdvHvZz3Y4ywssiRy6fAqBzh8CzI6JfAe2fFenJyGqQMDAHxl3Ri5y+BAduWMGVG735FcUrdVXCa1RpRf/7bGQVUYRsJphmSLD/KkpnVYGiH7QAwtlTShai0gAYkArp7KJE2XSDAqkzFW3Bxx+dYYpDsoog50ka0QP9z18/X+bzGq/XQVEejKt8jM9K2f41UEeDATFIq1miOlzZu/PlcRKtoD2S2JDjSmnaykVBtX05f2YBFZDs0ToZPrX8YN9Cx2U9W7mWrro7IC6dcQuNySRbpRMsGIATgHULClfF/vUlTUvP7iRBICfTsDVSE7NBTqLwSu5HdU3dMT/kj/qSy2F7InSHsi3sVBIMAkHTR5vGosjk5dj6OoRU6Q0n56JurXFQ6I5j2tUC9xjPRc2SWcZ2NrLMtYd7AHA4fh/87W0TjzSWFuy21vfaDvoIMKLbE3BTt9hytzd6qPv5CdZPpKh56FJs84kL+djOnOyCibd3SWgLrzf3tTBpTFsKU5MVqJvYoqdKOT9utBWHunwHSDvsdo/SPFV6h5PLDa+1kPe7TMedQfUg2Iu/kFP+S1C9eWdrIiKwu4vfvIYnB9nIvcN+JWDzzYwdDobDZrTgW4I5dUpslt/v9Px3RGvrag/64oO14horV0BMHIFRF+UURdxpYqJ7YYRlEPccRAcfExYg4Kk/5Y43rIRCzkx5scB/02ECez4NtuRb8cJn8idmpin4T40y4ypLMC42dznDbejGZCsCjSgYTLip9Uz4xlpM16dK2NcT8bx22/jqMxsRxxn1BhUcX09capc/m8lUHAVVIovUC2OD5HBhSQWo4iyF58wJ3c0BfipFp/BDOZnZcD9/RGd7sgnLsEsg46/i3Xu7wXJoOHkAOcbrb9eNKeOe/4zV5ibVIiwuIeP3LPuK0l/AArXsf16SBdVCx3D6VgKDenODI/IAi0mbSciDPbD47LRmvCf3Be5/Ju4xKH+09wkyt39Kwj79AQV2jTBlG/ih2QTI+eN6n2Ui2Z5mt714N9/6V9nZWX/azjMaxcyQNeLvRCSaujb4k1b3szhYWjF8ZyXHwlXKpsOo02knZtsNre8keO6Bbc3KNTsLy49YoCjDXk6mVQvd+quEaCR1aGvgbVS43FVZMkhkYzXuV4lGbFNTppncmgzSZR1msJ0DftO0XDQMqZ3bEblpcCimGwDMj8vNeuOiRfvHBeU9JQ5NA39oFTNuzRp5g9z4dPh2I0+W59ItUM02AXVlioiCv1sxnae1r6GV0wTJWc1vMVahWOi36X35C/iIX2YW85m+ehFCKyq10CE91EMX9Jx9vC5AsojxZCPbjbwCbY9T46de9SgqiHiOlTB9ivnsR5ryHcGaeCgO2CaDJQV3hqfpCsdLN45rRr05YakxZspVzsj9JoQ2rmiCVRAnG4TYPI4d+I3qGLW6hVIIMhFG/tipeCLnsDSMK3C9S20s+vMlM+I1+PKmPsE9t7KAUQx4Aui3miq8GKLciZAQIM2UGvK1JyqAL8qdmzRXeT5C2NWqjLKV2S1Ze5O2fQbueIXNhRNBT1ByYv19jwV42ThIt2LOdclIdRPzxKI16H8Wl97CYM4TBYBV21kADrES9Vb/G/8XPwa7NIRdzRUg+X6XPdt4YC3VqcpGIfC4t96nOV/flmeMuOhM7Tk/4fdjXYtj5wIfDOUNRTCUvKNjGCgg4pkBFyAc2hkX+vcH9nEC3NBTl9bJa6gP6OGr9IUE+yVSfGVbJ27Si4AyddUpagdk+r8TxacoPnC1Wc9rcX51cbx3y4IkTZe2fmdhoqqYkUZMMX75esOz5J4zDoE1zx9Q4OaEtbMKiTaa10DpU1K1PX76ygoiIIqfqUbke6uIBmjsWIB62YZRTNWb8NYtClmBGAcLVsPrYDiRfep35pL8lUZ5JvYzfwjDhgVmhbT0eI5QSqlrEC2xleC1oaVPd+aJrwv03IUl7iOxj/7c6wRsesJe7/U8tnSpjW64iQwSNOGb3S89SlreT5vbnO2R3nQICA13puLCOFvSJktk9HE7BmcNa1GxZ6hn6brw74wgURoskJW/eYkQRzg68MLXPao87XKJK/4FEjlUeZJf/x+ggXfaxVuni5ZjTlS31iNHY1phibbTD8+snBYT9koFacW5RXjhbGJQNS0Yc4JMRKrxIAKT3MyJQIQ5gfTg8b53BJNWW/gg3RqG3YUYq0nAZyB5k8z28pxZYazC9XKXk3yotBj5sRS+4Wgh3yxAJ5WbUyOHMPYCN7tABK4jEomdQbnV0t+kdNver+xo8L1Xagtj445XD8rPFM09ZEEMOmjEI55abQevwpRs9jmQ9VlONakk/CJAMgHuIsFRYBO3CzdM2KdZdO5/xRxpDhfLr9ETHimjUfIyUYylvGm9/XDZIbp4bhJzNbYszowtYrfWYuKTNwbUshg5qOOLCTTb1dy1Hy4vwLshxiHDoWVLhlHeUH3s8C31tkaSkw7nVCpCS/NLAeA7IdhdADLf5lH2nxHQl0iAgmupQw/cPhFrahG6L+S/OLuePvPGDrNgA/RJkOvVQ1y09BXAIskPCr8eKUS01+zIiS0Tu7kvTQ65SQIRCPbTiPzWmxH+gXAKSHGx9J41jakMzsS2zIYkuNelX3J0tvgZRL7r8MTnK1YHndB0KoAiWjG0wKLnoi4qv3xg/0NoJW5mE+saoQpl+NNs3ab24vDBFfAduPm1JXmUPWtiWx+b35KVSWIQu51XvZfb2HnoIBEtpAxaQvcL2fY2llW7HqgwPAHp30J+DLAIGtPLOokVCI3wAR7vwWCr3pyNnMNHrBeJCn7Wwg6GUvUea6PRLn8wWA6561m13PYPprhnx81zLhKGDPUfH1SDivQy0x8BJAWkdAjXKOMxd22tpUkAhbILPRUHOT0v1I+yPyf+Yy6gRc+8iA2oTpQ/wmkwuWgTPoe5Ujfmv6BbgL9y8nGm77JfA5TbEN7ATSPU8AmQDyR34xzm5u/aKDsH0GOMPpKAVsOqdRY0L9p4gePTXCEKVUEEuZ/g9o4RJVSRUfmr8vDmZmIPoUaQi8cOyWJm1vS8z53a1BnTxMx9+YIKDjPWlqK0ysSOLQK+pn1aAMLNtlSz8Ncy/iAPovlbfpWU6oHh8u5EfdnN6MfcXBfXVhTcH+AHuA0ctqMSUwIwYJKoZIhvcNAQkVMRYEFIdUIqMHnsbw4qagXcoNo1kyLQUgMDEwITAJBgUrDgMCGgUABBRZiRtnNMjOxBpuitzhBdqqembT6QQIX0RQdDle3b4CAggA
      - DataProtectionSettings:Password=password
      - DataProtectionSettings:DataProtectionStorage=Redis
      - DataProtectionSettings:RedisConnection=redis
      - DistributedCacheSettings:DistributedCacheType=redis
      - DistributedCacheSettings:ConfigurationNameOrConnectionString=redis
      - DemoSettings:IsDemo=true
      - DemoSettings:ApiKey=password
      - WebInfoSettings:IsWebInfoEnabled=true
      - WebInfoSettings:Secret=799c809f-9ca4-47ca-a9b1-3bce5c5215cf
    scale: 2

  www_arragro_com:
    image: docker.arragro.com/www.arragro.com:v0.0.8-alpha
    depends_on:
      - cms_arragro_com
    # logging:
    #   driver: none
    # ports:
    # - 5001:5001
    restart: always
    networks:
      - cms-net
      - redis-net
    environment:
      - ConnectionStrings:RedisConnection=redis:6379
      - ArragroCmsOptions:ApiUrl=http://cms_arragro_com:5000
      - ArragroCmsOptions:ApiKey=password
      - WebInfoSettings:IsWebInfoEnabled=true
      - WebInfoSettings:Secret=60aa42a9-6a6d-49ef-92c3-6c35ec124f0c
    scale: 2

  image_service:
    image: docker.arragro.com/imageservice:v0.0.5-alpha
    networks:
      - image-service-net
    scale: 3

  redis:
    image: redis:4.0.9-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    mem_limit: 128m
    networks:
      - redis-net
    volumes:
      - redis-data:/data

  azurite:
    image: arafato/azurite
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    networks:
      - azurite-net
    volumes:
      - azurite-data:/opt/azurite/folder

  postgres:
    restart: always
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD:'password1'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - cms-net

  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=support@arragro.com
      - PGADMIN_DEFAULT_PASSWORD=@rr@gr0
    networks:
      - cms-net
    volumes:
      - pgadmin:/root/.pgadmin

  # sql:
  #   restart: always
  #   image: microsoft/mssql-server-linux:2017-latest
  #   ports:
  #     - 1433:1433
  #   environment:
  #     - "ACCEPT_EULA=Y"
  #     - "SA_PASSWORD=@rr@gr0SuperPassword1"
  #   volumes:
  #     - sql-data:/var/opt/mssql
  #   mem_limit: "2048m"
  #   networks:
  #     - cms-net

networks:
  redis-net:
  image-service-net:
  azurite-net:
  cms-net:

volumes:
  redis-data:
  azurite-data:
  database:
  pgadmin:
  # sql-data:
